### ISSUE TITLE
Pass constom arguments to webdriver through config  

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/xenon#7]
Sometimes we need to configure webdriver binary (geckodriver/chromedriver etc.). through arguments.

For example path to executable (firefox/chrome) since it may have not standard location.

As I see currently we pass only port which handled internally.

https://github.com/stevepryde/xenon/blob/91fef580287c438b43d3aacf545d5282e95f346f/src/service.rs#L21-L32

We could add a list of specific options or a custom list which may be benefitial

I'll tackle it later if you don't mind and if you consider that's suitable change.

Actually people could create a bash script or something like that and just put a path to it in a config instead of a real binary. It would solve the issue. But it would be necessary for them to deal with arguments which you set up which is not nice (maybe)

**Comment by stevepryde** [comment]
Sounds good to me
